server:
  port: 8080

spring:
  datasource:
    username: springframwork
    password: springframwork
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
 




