server:
  port: 8080
  

spring:
  datasource:
    username: springframwork
    password: springframwork
    url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = orcl)))
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
mybatis:
  mapper-locations: classpath:mapping/**/*Mapper.xml
  configLocation: classpath:mapping/mybatis-config.xml
  
#日志配置项
#logging:
#日志输出地址：   path: /Users/jackie/workspace/rome/ 
#日志输出文件地址：   file: springboot-dev.log

#日志配置项
logging:
  level:    root: debug



